name: fitness_app
description: "A Flutter application for fitness management with features like user authentication, real-time updates, and offline support."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  flutter_local_notifications: ^20.1.0
  flutter_dotenv: ^6.0.0
  device_info_plus: ^12.2.0
  permission_handler: ^12.0.1
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.5
  flutter_app_installer: ^1.0.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  mutex: ^3.1.0
  pub_semver: ^2.2.0
  socket_io_client: ^3.1.2
  flutter_emoji_feedback: ^1.0.3
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/GSS_gym.png"
  image_path: "assets/icon/GSS_gym.png"


flutter:
  uses-material-design: true
  assets:
    - connect.env
