const AUDIT_EVENT_NAMES = Object.freeze({
  AUTH: Object.freeze({
    ACCESS_TOKEN_REJECTED: 'auth.access_token.rejected',
    LOGIN_BLOCKED: 'auth.login.blocked',
    LOGIN_LOCKED: 'auth.login.locked',
    LOGIN_FAILED: 'auth.login.failed',
    LOGIN_SUCCEEDED: 'auth.login.success',
    LOGOUT_COMPLETED: 'auth.logout.completed',
    QR_REQUESTED: 'auth.qr_request.requested',
    PUBLIC_ACCESS_REQUESTED: 'auth.public_access.requested',
    QR_DENIED: 'auth.qr.denied',
    QR_REVEALED: 'auth.qr_request.revealed',
    USER_REQUEST_RESOLVED: 'auth.approval.resolved',
    PASSWORD_CHANGE_BLOCKED: 'auth.password_change.blocked',
    PASSWORD_CHANGE_FAILED: 'auth.password_change.failed',
    PASSWORD_CHANGE_LOCKED: 'auth.password_change.locked',
    PASSWORD_CHANGE_DENIED: 'auth.password_change.denied',
    PASSWORD_CHANGE_SUCCEEDED: 'auth.password_change.success',
    PASSWORD_CHANGE_SUCCESS: 'auth.password_change.success',
    PASSWORD_CHANGE_REQUESTED: 'auth.password_change.requested',
    REFRESH_TOKEN_REJECTED: 'auth.refresh.rejected',
    REFRESH_TOKEN_ROTATED: 'auth.refresh.rotated',
    REFRESH_TOKEN_FAILED: 'auth.refresh.failed',
    TWO_FACTOR_CHALLENGE_ISSUED: 'auth.two_factor.challenge_issued',
    TWO_FACTOR_BLOCKED: 'auth.two_factor.blocked',
    TWO_FACTOR_FAILED: 'auth.two_factor.failed',
    TWO_FACTOR_VERIFIED: 'auth.two_factor.verified',
  }),
  MAIN: Object.freeze({
    USER_CREATED: 'main.user.created',
    USER_UPDATED: 'main.user.updated',
    USER_SECURITY_RESET: 'main.user.security_reset',
    USER_DELETED: 'main.user.deleted',
    USER_REQUEST_RESOLVED: 'main.user.request.resolved',
    PERMISSION_UPDATED: 'main.permission.updated',
    CAMP_ACCESS_UPDATED: 'main.camp_access.updated',
    CAMP_CREATED: 'main.camp.created',
    CAMP_UPDATED: 'main.camp.updated',
    CAMP_DELETED: 'main.camp.deleted',
    CAMP_IMPORTED: 'main.camp.imported',
  }),
  BICYCLES: Object.freeze({
    BIKE_CREATED: 'bicycles.bike.created',
    BIKE_UPDATED: 'bicycles.bike.updated',
    BIKE_DELETED: 'bicycles.bike.deleted',
    BIKE_IMPORTED: 'bicycles.bike.imported',
    BIKE_RENTED: 'bicycles.bike.rented',
    BIKE_RETURNED: 'bicycles.bike.returned',
    HELMET_CREATED: 'bicycles.helmet.created',
    HELMET_UPDATED: 'bicycles.helmet.updated',
    HELMET_DELETED: 'bicycles.helmet.deleted',
    HELMET_IMPORTED: 'bicycles.helmet.imported',
    MOBILE_APP_DOWNLOADED: 'bicycles.mobile_app.downloaded',
  }),
  LAUNDRY: Object.freeze({
    MOBILE_APP_DOWNLOADED: 'laundry.mobile_app.downloaded',
  }),
  ASSETS: Object.freeze({
    MOBILE_APP_DOWNLOADED: 'assets.mobile_app.downloaded',
  }),
  SECURITY: Object.freeze({
    SESSION_INVALIDATED: 'security.session.invalidated',
  }),
  REALTIME: Object.freeze({
    FORCED_DISCONNECT: 'realtime.connection.forced_disconnect',
    SUBSCRIPTION_REJECTED: 'realtime.subscription.rejected',
    ROOM_REQUEST_REJECTED: 'realtime.room_request.rejected',
    ROOM_ACCESS_DOWNGRADED: 'realtime.room_access.downgraded',
  }),
});

module.exports = { AUDIT_EVENT_NAMES };
