const MIGRATION_PHASES = Object.freeze({
  EXPAND: 'expand',
  BACKFILL: 'backfill',
  SWITCH: 'switch',
  CONTRACT: 'contract',
});

const MIGRATION_RISK = Object.freeze({
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
});

const manifest = Object.freeze({
  '0001_bootstrap_extensions_and_schema': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Initial schema bootstrap for a new environment.',
    rollback: 'Rollback by restoring from the pre-deploy backup or by tearing down the fresh environment.',
  },
  '0002_normalize_auth_tables': {
    phase: MIGRATION_PHASES.SWITCH,
    risk: MIGRATION_RISK.HIGH,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Renames auth tables and columns to the normalized shape.',
    rollback: 'Deploy a forward corrective migration or restore from backup if already applied in production.',
  },
  '0003_harden_auth_constraints': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Adds auth constraints and supporting columns.',
    rollback: 'Use a dedicated forward migration to relax or replace constraints after validation.',
  },
  '0004_auth_indexes_and_request_guards': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds auth indexes and request guard structures.',
    rollback: 'Remove or replace indexes in a forward migration if needed.',
  },
  '0005_normalize_domain_tables': {
    phase: MIGRATION_PHASES.SWITCH,
    risk: MIGRATION_RISK.HIGH,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Normalizes domain tables and naming conventions.',
    rollback: 'Use backup restore or a forward corrective migration after rehearsing on staging.',
  },
  '0006_harden_domain_constraints_and_indexes': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Adds domain constraints and hot-path indexes.',
    rollback: 'Use a forward migration to adjust constraints or remove problematic indexes.',
  },
  '0007_operational_maintenance': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Creates maintenance tracking tables and routines.',
    rollback: 'Deploy a forward migration to disable routines or restore from backup if needed.',
  },
  '0008_add_user_account_lock': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds the account lock flag on users.',
    rollback: 'Safe to ignore; future code can tolerate the extra column until a cleanup migration.',
  },
  '0009_auth_token_version_and_refresh_jti': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Adds token-version and JTI support to auth sessions.',
    rollback: 'Use a forward migration after validating token compatibility in staging.',
  },
  '0010_refresh_session_hardening': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Adds refresh-session metadata and revocation constraints.',
    rollback: 'Use a forward migration to relax checks or fall back to backup restore if required.',
  },
  '0011_repository_hot_path_indexes': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds repository hot-path indexes.',
    rollback: 'Drop the index in a follow-up migration if it regresses performance.',
  },
  '0012_bicycle_actions_and_nfc': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds bicycle NFC codes, permissions, and action hot-path indexes.',
    rollback: 'Keep the additive column until a follow-up migration can remove dependent code safely.',
  },
  '0013_bicycle_repair_assignments': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Allows active bicycle repair assignments without a soldier.',
    rollback: 'Return repair bicycles before tightening the assignment constraint in a follow-up migration.',
  },
  '0014_helmet_nfc_and_permissions': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds helmet NFC codes and separate helmet management permissions.',
    rollback: 'Keep the additive column and permissions until a follow-up migration can remove dependent code safely.',
  },
  '0015_accommodation_management_permissions': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds Accommodation and keys management permissions.',
    rollback: 'Keep the additive permissions until a follow-up migration can remove dependent code safely.',
  },
  '0016_key_nfc_codes': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds NFC codes to accommodation keys.',
    rollback: 'Keep the additive column until a follow-up migration can remove dependent code safely.',
  },
  '0017_soldier_accommodation_items_permissions': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds soldier accommodation and additional item management permissions.',
    rollback: 'Keep the additive columns and permissions until dependent code can be removed safely.',
  },
  '0018_soldier_upcoming_schedule_constraint': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Prevents future soldier upcoming release dates before upcoming accommodation dates.',
    rollback: 'Drop or replace the check constraint in a forward migration if scheduling rules change.',
  },
  '0019_laundry_management_permission': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds the Laundry workspace permission for fresh environments.',
    rollback: 'Keep the additive permission until dependent code can be removed safely.',
  },
  '0020_laundry_bag_rfid_codes': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds RFID codes to laundry bags.',
    rollback: 'Keep the additive column until a follow-up migration can remove dependent code safely.',
  },
  '0021_laundry_action_permissions': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds granular Laundry action permissions.',
    rollback: 'Keep the additive permissions until dependent code can be removed safely.',
  },
  '0022_unique_additional_item_laundry_bags': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Prevents the same laundry bag from being linked to multiple additional item rows.',
    rollback: 'Drop the partial unique index in a forward migration if the business rule changes.',
  },
  '0023_laundry_mobile_app_permission': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds permission for downloading the laundry mobile app.',
    rollback: 'Keep the additive permission until dependent code can be removed safely.',
  },
  '0026_clean_item_warehouses': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Adds large/small warehouse placement to clean items and normalizes clean item event timestamps.',
    rollback: 'Use a forward migration to merge or remove warehouse-specific clean item rows.',
  },
  '0027_admin_permission_rename': {
    phase: MIGRATION_PHASES.SWITCH,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Renames Add system permission to Admin permission while keeping Full permission separate.',
    rollback: 'Use a forward migration to restore the previous permission name if older code must be redeployed.',
  },
  '0028_restrict_asset_type_delete': {
    phase: MIGRATION_PHASES.SWITCH,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Changes assets.type_id to restrict asset type deletion while assets still reference the type.',
    rollback: 'Use a forward migration to restore the previous delete behavior if the business rule changes.',
  },
  '0029_assets_mobile_app_permission': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary: 'Adds permission for downloading the assets mobile app.',
    rollback: 'Keep the additive permission until dependent code can be removed safely.',
  },
  '0030_asset_management_permission': {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.LOW,
    safeOnBoot: true,
    requiresManualGate: false,
    summary:
      'Adds Asset management page access and granular Assets action permissions while preserving legacy grants.',
    rollback: 'Keep the additive permissions until all users have been migrated safely.',
  },
});

function getMigrationMeta(version) {
  return manifest[version] || {
    phase: MIGRATION_PHASES.EXPAND,
    risk: MIGRATION_RISK.MEDIUM,
    safeOnBoot: false,
    requiresManualGate: true,
    summary: 'Unclassified migration. Treat as manual-gate only until reviewed.',
    rollback: 'Rollback via restore or a dedicated forward migration after review.',
  };
}

module.exports = {
  MIGRATION_PHASES,
  MIGRATION_RISK,
  migrationManifest: manifest,
  getMigrationMeta,
};
